### ISSUE TITLE
Re-write: Sign-up page

### ISSUE THREAD

**Issue by AKissMail** [aidportaliug/IUG-projects#14]
Feide is not implemented yet. The button for Feide should be easy to add. 

![Screenshot from 2024-01-29 19-49-18](https://github.com/Kamkarls/IUG-projects/assets/69756846/72f6ac96-f0ae-4c92-8a07-53d4ec299837)

**Comment by ESPR07** [comment]
Fixing the sign in basically leads to fixing this as they uses the same class names, so I can take on both :)
